'use client';
import Link from 'next/link';
import {useRef} from 'react';
import {Heart,BookmarkSimple,MapPin,Star,ArrowUpRight,CheckCircle,CaretLeft,CaretRight,ChatCircle,Briefcase,CurrencyRub,ImageSquare,Tag,UsersThree,DownloadSimple,ShareNetwork,Eye} from '@phosphor-icons/react';
import {profiles,projects,mediaById,creditsFor,reviews} from '@/data/seed';
import {cityName} from '@/data/catalog';
import type {Profile,Project,Price} from '@/types/domain';
import {useApp} from '@/components/navigation/app-shell';
export const formatPrice=(p:Price)=>p.kind==='request'?'По запросу':`${p.kind==='from'?'от ':''}${(p.from??0).toLocaleString('ru-RU')} ${p.currency==='RUB'?'₽':p.currency==='KZT'?'₸':'AED'} / ${p.unit}`;
export function ProjectCard({project,mediaIndex=0,variant='standard'}:{project:Project;mediaIndex?:number;variant?:'standard'|'visual'}){const app=useApp();const m=mediaById(project.mediaIds[mediaIndex%project.mediaIds.length]);const lead=profiles.find(p=>p.id===project.leadProfileId)!;const count=creditsFor(project.id).length;const liked=app.likes.includes(project.id);return <article className={`card project-card ${variant==='visual'?'project-card-visual':''}`}><Link className="media-link" aria-label={variant==='visual'?project.title:undefined} href={`/projects/${project.slug}?media=${mediaIndex}&from=feed`}><img src={m.src} alt={`${project.title}: ${m.alt}`} loading="lazy"/><span className="demo-label">Демо-визуал</span></Link>{variant==='standard'&&<div className="card-body"><div className="between project-card-title-row"><Link className="card-title" href={`/projects/${project.slug}`}>{project.title}</Link><button className="icon-btn" style={{minWidth:36,minHeight:36}} aria-label={`Сохранить проект ${project.title}`} title="Сохранить проект" onClick={()=>app.open('save',{projectId:project.id})}><BookmarkSimple size={18}/></button></div><div className="meta icon-meta"><span><MapPin size={13}/> {cityName(project.city)}</span><span><Tag size={13}/> {project.eventType}</span></div><div className="project-card-tags" aria-label="Стили проекта">{project.styles.slice(0,2).map(style=><Link className="chip" href={`/search?q=${encodeURIComponent(style)}`} key={style}>{style}</Link>)}</div><div className="row project-card-lead"><img className="avatar" style={{width:30,height:30}} src={lead.avatar} alt=""/><Link className="meta" href={`/profiles/${lead.slug}`}>{lead.name}</Link><Link className="meta icon-meta" href={`/projects/${project.slug}#team`}><UsersThree size={14}/> +{count-1} участников</Link></div><div className="between project-card-actions"><button className="icon-btn" style={{minWidth:36,minHeight:36}} aria-label={liked?'Убрать реакцию':'Поставить реакцию'} title={liked?'Убрать реакцию':'Поставить реакцию'} onClick={()=>app.toggleLike(project.id)}><Heart size={18} weight={liked?'fill':'regular'} color={liked?'var(--brand-pro)':undefined}/></button><span className="meta icon-meta"><Heart size={14}/> {project.reactions+(liked?1:0)} реакций</span><Link className="project-card-open" href={`/projects/${project.slug}`}>Открыть <ArrowUpRight size={16}/></Link></div></div>}</article>}
export function ProfileCard({profile}:{profile:Profile}){const app=useApp();const local=profile.city===app.city;const reviewCount=reviews.filter(r=>r.profileId===profile.id).length;const kind=profile.type==='venue'?'Площадка':profile.type==='company'?'Команда':profile.type==='team'?'Команда':'Специалист';const travel=local?'В вашем городе':profile.travel==='local'?`Только в ${cityName(profile.city)}`:profile.travel==='countrywide'?'По всей России':profile.travel==='international'?'Международные проекты':'Выезжает';return <article className="card profile-card"><Link className="profile-card-cover" href={`/profiles/${profile.slug}`}><img className="media" src={profile.cover} alt={`Демо-обложка профиля ${profile.name}`} loading="lazy"/><span className="profile-card-kind">{kind}</span></Link><div className="card-body"><img className="avatar" src={profile.avatar} alt=""/><div className="between profile-card-name"><Link href={`/profiles/${profile.slug}`} className="card-title">{profile.name}</Link>{profile.verified&&<span className="badge verified" title="Профиль проверен в demo"><CheckCircle size={14}/> Проверен</span>}</div><div className="meta icon-meta"><span><Briefcase size={13}/> {profile.specialty}</span><span><MapPin size={13}/> {cityName(profile.city)}</span></div><div className="facts" style={{margin:'12px 0'}}><span className="badge"><MapPin size={13}/> {travel}</span><span className="badge"><Star size={13} weight="fill"/> {profile.rating.toFixed(1)}</span><span className="badge"><ChatCircle size={13}/> {reviewCount} отзывов</span></div><div className="profile-card-tags" aria-label="Стили профиля">{profile.styles.slice(0,2).map(style=><span className="chip" key={style}>{style}</span>)}</div><div className="between profile-card-footer"><b style={{fontSize:13}}>{formatPrice(profile.price)}</b><Link className="profile-card-open" href={`/profiles/${profile.slug}`} aria-label={`Открыть профиль ${profile.name}`}>Открыть <ArrowUpRight size={17}/></Link></div></div></article>}

function profileMedia(profile:Profile,count:number){const ids=profile.projectIds.flatMap(id=>projects.find(p=>p.id===id)?.mediaIds??[]);return (ids.length?ids:[projects[0].mediaIds[0]]).slice(0,count)}
export function ProCatalogCard({profile,variant='standard'}:{profile:Profile;variant?:'standard'|'compact'|'visual'}){const media=profileMedia(profile,variant==='compact'?9:4);const extra=Math.max(0,profile.projectIds.reduce((n,id)=>n+(projects.find(p=>p.id===id)?.mediaIds.length??0),0)-media.length);return <article className={`card pro-catalog-card pro-catalog-${variant}`}><Link className="pro-catalog-link" aria-label={profile.name} href={`/profiles/${profile.slug}`}><div className="pro-catalog-head"><img className="pro-catalog-avatar" src={profile.avatar} alt=""/><div className="pro-catalog-name"><b>{profile.name}</b><span className="icon-meta"><Briefcase size={12}/> {profile.specialty}<MapPin size={12}/> {cityName(profile.city)}</span></div>{profile.verified&&<CheckCircle className="pro-catalog-verified" size={17} color="var(--brand-blue)" weight="fill"/>}</div><div className="pro-catalog-metrics"><span className="pro-catalog-price icon-meta" title="Стоимость"><CurrencyRub size={14}/><b>{formatPrice(profile.price)}</b></span><span className="icon-meta"><Star size={14} weight="fill"/> {profile.rating.toFixed(1)}</span><span className="icon-meta"><ChatCircle size={14}/> {reviews.filter(r=>r.profileId===profile.id).length}</span><span className="icon-meta"><Briefcase size={14}/> {profile.projectIds.length}</span></div><div className="pro-catalog-gallery">{media.map((id,i)=><img key={`${id}-${i}`} src={mediaById(id).src} alt="" loading="lazy"/>)}{extra>0&&<span className="pro-catalog-more"><ImageSquare size={13}/> +{extra}</span>}</div></Link></article>}

export function ProShowcaseCard({profile,variant='wide'}:{profile:Profile;variant?:'wide'|'compact'|'row'}){const projectIds=profile.projectIds.slice(0,2);const thumbs=projectIds.flatMap(id=>projects.find(p=>p.id===id)?.mediaIds??[]).slice(0,4);const media=thumbs.length?thumbs:[projects[0].mediaIds[0]];return <Link className={`pro-showcase-card pro-showcase-${variant}`} href={`/profiles/${profile.slug}`}><div className="pro-showcase-head"><img className="avatar" src={profile.avatar} alt=""/><div className="pro-showcase-name"><b>{profile.name}</b><span className="icon-meta"><MapPin size={13}/> {cityName(profile.city)}</span></div>{profile.verified&&<CheckCircle size={18} color="var(--brand-blue)" weight="fill"/>}</div><div className="pro-showcase-metrics"><span className="icon-meta" title="Стоимость"><CurrencyRub size={15}/> от</span><span className="icon-meta"><Star size={15} weight="fill"/> {profile.rating.toFixed(1)}</span><span className="icon-meta"><ChatCircle size={15}/> {reviews.filter(r=>r.profileId===profile.id).length}</span><span className="icon-meta"><Briefcase size={15}/> {profile.projectIds.length}</span></div><div className="pro-showcase-media">{media.map((id,i)=><img key={`${id}-${i}`} src={mediaById(id).src} alt=""/>)}{profile.projectIds.length>2&&<span className="icon-meta"><ImageSquare size={13}/> +{profile.projectIds.length*4-media.length}</span>}</div></Link>}

export function ProShowcaseRail({profiles:items}:{profiles:Profile[]}){const ref=useRef<HTMLDivElement>(null);const scroll=(direction:number)=>ref.current?.scrollBy({left:direction*620,behavior:'smooth'});return <div className="pro-showcase-shell"><button className="pro-rail-arrow pro-rail-prev" aria-label="Предыдущие профессионалы" onClick={()=>scroll(-1)}><CaretLeft size={20}/></button><div className="pro-showcase-rail" ref={ref}>{items.map((p,i)=><ProShowcaseCard key={`${p.id}-${i}`} profile={p} variant="wide"/>)}</div><button className="pro-rail-arrow pro-rail-next" aria-label="Следующие профессионалы" onClick={()=>scroll(1)}><CaretRight size={20}/></button></div>}


export function VisualProjectCard({project,mediaIndex=0}:{project:Project;mediaIndex?:number}){
  const app=useApp()
  const m=mediaById(project.mediaIds[mediaIndex%project.mediaIds.length])
  const lead=profiles.find(p=>p.id===project.leadProfileId)!
  const liked=app.likes.includes(project.id)
  const share=async()=>{
    try{await navigator.clipboard.writeText(location.origin+'/projects/'+project.slug);app.toast('Ссылка на проект скопирована')}
    catch{app.toast('Ссылка на проект готова к копированию')}
  }
  return <article className="card project-card project-card-visual">
    <Link className="media-link" aria-label={project.title} href={'/projects/'+project.slug+'?media='+mediaIndex+'&from=feed'}>
      <img src={m.src} alt={project.title+': '+m.alt} loading="lazy"/>
      <span className="demo-label">Демо-визуал</span>
    </Link>
    <div className="visual-card-actions" aria-label={'Действия проекта «'+project.title+'»'}>
      <button className="icon-btn" aria-label={liked?'Убрать реакцию':'Поставить реакцию'} title={liked?'Убрать реакцию':'Поставить реакцию'} onClick={()=>app.toggleLike(project.id)}><Heart size={17} weight={liked?'fill':'regular'} color={liked?'var(--brand-pro)':undefined}/></button>
      <span className="visual-card-stat" title="Реакции"><Heart size={14}/> {project.reactions+(liked?1:0)}</span>
      <span className="visual-card-stat" title="Просмотры"><Eye size={14}/> {Math.max(120,project.reactions*18)}</span>
      <button className="icon-btn" aria-label={'Сохранить проект '+project.title} title="Сохранить проект" onClick={()=>app.open('save',{projectId:project.id})}><BookmarkSimple size={17}/></button>
      <a className="icon-btn" aria-label={'Скачать обложку проекта '+project.title} title="Скачать изображение" href={m.src} download onClick={e=>e.stopPropagation()}><DownloadSimple size={17}/></a>
      <Link className="icon-btn" aria-label={'Открыть автора проекта '+project.title} title="Автор проекта" href={'/profiles/'+lead.slug} onClick={e=>e.stopPropagation()}><UsersThree size={17}/></Link>
      <button className="icon-btn" aria-label={'Поделиться проектом '+project.title} title="Поделиться" onClick={share}><ShareNetwork size={17}/></button>
    </div>
  </article>
}
